### ISSUE TITLE
Cannot select Limitless Bardic Performance on Thundercaller

### ISSUE THREAD

**Issue by Prizzels** [Truinto/DarkCodex#215] opened 2023-03-02 21:51 UTC
X Bardic Performance
v Bardic Performance

I see this under requirements ultimately making it unselectable. When browsing similar mythic abilities, none have this double requirement text. 

Afaik also applies to  Sensei but worked fine for Skalds.

**Comment by Prizzels** [comment] 2023-03-03 17:27
Is it possible that a game started with a previous version would carry it over? I'm doing DLC runs and have Codex fully updated but I guess its technically one save.

**Comment by Truinto** [comment] 2023-03-03 20:37
Nope. This will instantly updated and is not stored in the save file. This is a duplicate of  #204
I am very confused on how it wouldn't work.

**Comment by Truinto** [comment] 2023-03-04 19:30
![pic](https://user-images.githubusercontent.com/47917181/222925231-91d790d9-c09c-4877-8427-589a365e70ec.jpg)
No idea what's going on your end. If you find a lead, let me know.

**Closed by Truinto** 2023-03-04 19:30 UTC
Labels: bug
