### ISSUE TITLE
Destructive Dispel (Kineticist) DC=10, no scaling

### ISSUE THREAD

**Issue by 0utrider** [Truinto/DarkCodex#24] opened 2022-01-16 21:37 UTC
Hello - thanks for the awesome mod!

I noticed that my L19 Kineticist wasn't getting the Destructive Dispel off to cause stuns, only sickened. When I looked closer, I see that the DC is just 10, with no modifiers. [Example](https://i.imgur.com/ol1CjZT.jpg)

This might apply to regular spells using DD, but I haven't tested it yet.

Thank you!

**Comment by Truinto** [comment] 2022-01-23 20:02
What feature/ability are you using to dispel? The only infusion I can think of does not apply Destructive Dispel.

**Comment by 0utrider** [comment] 2022-01-28 08:59
> What feature/ability are you using to dispel? The only infusion I can think of does not apply Destructive Dispel.

**Unraveling Infusion** - it does apply the dispel effect, and even the Destructive Dispel as you can see above in my screenshot. It wasn't applying it before I had the mod turned on, so honestly I thought that was something that the mod fixed, but just that it wasn't considering the proper scaling of the DC.

Maybe Owlcat added it but forgot the scaling?

**Comment by Truinto** [comment] 2022-01-28 16:22
I didn't consider an update from Owlcat. Guess I have to renew my data-mined blueprints. Not sure why this would happen. Although it's not the first dispel feature I found that uses a flat DC 10. Dispelling Strike for rogues had the same issue in Kingmaker.

**Comment by 0utrider** [comment] 2022-01-28 17:37
Yeah Dispelling Strike had that issue in WotR too at one point - I wasn't sure if it was your mod or a patch that fixed it, but I could swear I saw it fixed for the Rogue and Slayer.

I'll run some tests again once I get back up and running; just did a fresh Win11 install so I'm not quite done migrating yet :)

**Comment by Truinto** [comment] 2022-01-28 19:42
Win11? All I know about it is that it's unfinished, has compatibility issues, and spies even more than Win10 already did. Off-topic, but it really surprises me that anyone wants to use it.

About Dispelling Strike, I have made no changes that would affect it. Guess it was fixed by Owlcat.

**Comment by 0utrider** [comment] 2022-01-28 21:39
> Win11? All I know about it is that it's unfinished, has compatibility issues, and spies even more than Win10 already did. Off-topic, but it really surprises me that anyone wants to use it.
Yeah, but I'm in IT (cybersecurity), so it's my way to learn it. I use Windows for gaming primarily though; anything I want to do that I'm worried about privacy I use my my 'nix boxes anyway.



> About Dispelling Strike, I have made no changes that would affect it. Guess it was fixed by Owlcat.
Definitely hard to keep up with. All I know is that I've been much happier with my kineticists since finding this mod - especially with selective metakinesis, oh man it's good. :)

**Comment by Truinto** [comment] 2022-03-26 23:11
Destructive dispel was patched by Owlcat. Hopefully it works as intended now. If not, it's a base game issue.

**Comment by Truinto** [comment] 2022-04-02 09:07
So the logic is:
- stat bonus of the highest level of spell casting class
- sum all spell casting levels

Kineticist is no spell casting class. So you get a bonus of +0. With the next update I will change the logic to:
- highest mental stat bonus
- sum all class levels

**Closed by Truinto** 2022-04-02 09:07 UTC
Labels: question
