### ISSUE TITLE
Making Assassin worth it

### ISSUE THREAD

**Issue by SethStormR** [Truinto/DarkCodex#141] opened 2022-10-02 06:22 UTC
Hello,
I have a request for Myth feature. At current state the prestige class "Assassin" is pretty much useless as the most enemies you encountering have immunity to poison. So what about a myth feature that give the assassin to overcome poison immunity?

regards,

**Comment by Truinto** [comment] 2022-10-02 13:20
Duplicate of https://github.com/Truinto/DarkCodex/issues/79
MagicTime has that feat already https://github.com/Stari0n/MagicTime/releases
Cheers :)

**Closed by Truinto** 2022-10-02 13:20 UTC
Labels: enhancement
