### ISSUE TITLE
Battle Prowess with Limitless Performance

### ISSUE THREAD

**Issue by Zane-Sutton** [Truinto/DarkCodex#233] opened 2023-03-25 13:57 UTC
Currently 'battle prowess' from the battle scion skald disables itself out of combat, making comboing it with limitless performance not so great because you can't keep the buffs (particularly the permanant haste with master skald) up permanantly.

Quality of life request for the ability to keep battle prowess on between fights, and to not disable after combat completes.

**Comment by Truinto** [comment] 2023-03-25 14:03
Duplicate of #230 
I was hoping the change would fix this. Did you test this with the current update?

**Comment by Zane-Sutton** [comment] 2023-03-25 14:07
oh my mistake mate, I'm a complete dingus. Didn't realise this was already fixed in another update.
Let me download the latest and give it a try

**Comment by Zane-Sutton** [comment] 2023-03-25 14:23
Yep, looks like it works just fine. Time to take this as a sign to get some sleep.
Loving the mod so far otherwise, Thanks for all the cool changes!

**Comment by Truinto** [comment] 2023-03-26 02:16
👍

**Closed by Truinto** 2023-03-26 02:16 UTC
Labels: duplicate, enhancement
